steps:
  # 1. Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/playtomic-notifier:$COMMIT_SHA'
      - '.'

  # 2. Push the container image to Google Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/playtomic-notifier:$COMMIT_SHA'

  # 3. Deploy the container image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'playtomic-notifier' # The name of your Cloud Run service
      - '--image=gcr.io/$PROJECT_ID/playtomic-notifier:$COMMIT_SHA'
      - '--region=us-central1' # Change to your preferred region
      - '--platform=managed'
      - '--allow-unauthenticated' # Or configure authentication as needed
      - '--set-env-vars=PLAYTOMIC_USER=your-playtomic-user,PLAYTOMIC_PASS=your-playtomic-pass,SLACK_BOT_TOKEN=your-slack-token,SLACK_CHANNEL_ID=your-channel-id,BOOKING_FILTER=Padel'

images:
  - 'gcr.io/$PROJECT_ID/playtomic-notifier:$COMMIT_SHA'
