name: Build and Deploy to Cloud Run

on:
  push:
    branches:
      - main

env:
  # ------------------------------------------------------------------------------------
  # REQUIRED GITHUB SECRETS
  # ------------------------------------------------------------------------------------
  # GCP_PROJECT_ID: Your Google Cloud project ID.
  # GCP_WORKLOAD_IDENTITY_PROVIDER: The full name of the Workload Identity Provider.
  #   (e.g., projects/123456789/locations/global/workloadIdentityPools/my-pool/providers/my-provider)
  # GCP_SERVICE_ACCOUNT: The email of the service account to use.
  #   (e.g., my-service-account@my-project.iam.gserviceaccount.com)
  #
  # ------------------------------------------------------------------------------------
  # CUSTOMIZABLE ENVIRONMENT VARIABLES
  # ------------------------------------------------------------------------------------
  GCP_REGION: "europe-west3" # e.g.,
  ARTIFACT_REGISTRY_REPO: "ideal-tribble-repo" # Your Artifact Registry repository name
  IMAGE_NAME: "ideal-tribble"
  TERRAFORM_STATE_BUCKET: "ideal-tribble-terraform-state"

jobs:
  test:
    name: Run Unit & Integration Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.24" # Specify your Go version

      - name: Run Tests
        run: go test -v -race ./...

  build-and-push:
    name: Build and Push Docker Image
    needs: test # This job depends on the 'test' job
    runs-on: ubuntu-latest
    permissions:
      contents: "read"
      id-token: "write"

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Authenticate to Google Cloud
        uses: "google-github-actions/auth@v2"
        with:
          workload_identity_provider: "${{ secrets.GCP_WORKLOAD_IDENTITY_PROVIDER }}"
          service_account: "${{ secrets.GCP_SERVICE_ACCOUNT }}"

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: "${{ env.GCP_REGION }}-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/${{ env.ARTIFACT_REGISTRY_REPO }}/${{ env.IMAGE_NAME }}:${{ github.sha }}"
          cache-from: type=gha
          cache-to: type=gha,mode=max

  deploy-with-terraform:
    name: Deploy to Cloud Run via Terraform
    needs: build-and-push
    runs-on: ubuntu-latest
    permissions:
      contents: "read"
      id-token: "write"

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Authenticate to Google Cloud
        uses: "google-github-actions/auth@v2"
        with:
          workload_identity_provider: "${{ secrets.GCP_WORKLOAD_IDENTITY_PROVIDER }}"
          service_account: "${{ secrets.GCP_SERVICE_ACCOUNT }}"

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        id: init
        run: |
          terraform -chdir=./terraform init \
            -backend-config="bucket=${{ env.TERRAFORM_STATE_BUCKET }}"

      - name: Terraform Apply
        id: apply
        run: |
          terraform -chdir=./terraform apply -auto-approve \
            -var="gcp_project_id=${{ secrets.GCP_PROJECT_ID }}" \
            -var="image_name=${{ env.GCP_REGION }}-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/${{ env.ARTIFACT_REGISTRY_REPO }}/${{ env.IMAGE_NAME }}:${{ github.sha }}"
